export const windData = [
    {
        "time": "1:00",
        "mon": 110,
        "tue": 10,
        "wed": 1,
        "thur": 5,
        "fri": 3,
        "sat": 2,
        "sun": 1,
    },
    {
        "time": "2:00",
        "mon": 10,
        "tue": 0,
        "wed": 9,
        "thur": 5,
        "fri": 10,
        "sat": 2,
        "sun": 3,
    },
    {
        "time": "3:00",
        "mon": 10,
        "tue": 10,
        "wed": 8,
        "thur": 5,
        "fri": 2,
        "sat": 3,
        "sun": 4,
    },
    {
        "time": "4:00",
        "mon": 70,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 3,
        "sun": 3,
    },
    {
        "time": "5:00",
        "mon": 10,
        "tue": 6,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 2,
        "sun": 0,
    },
    {
        "time": "6:00",
        "mon": 6,
        "tue": 1,
        "wed": 2,
        "thur": 4,
        "fri": 1,
        "sat": 2,
        "sun": 2,
    },
    {
        "time": "7:00",
        "mon": 40,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 2,
        "sun": 3,
    },
    {
        "time": "8:00",
        "mon": 47,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 5,
        "sun": 3,
    },
    {
        "time": "9:00",
        "mon": 8,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 9,
        "sun": 3,
    },
    {
        "time": "10:00",
        "mon": 10,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 8,
        "sun": 3,
    },
    {
        "time": "11:00",
        "mon": 60,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 6,
        "sun": 3,
    },
    {
        "time": "12:00",
        "mon": 8,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 3,
        "sun": 3,
    },
    {
        "time": "13:00",
        "mon": 4,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 1,
        "sun": 3,
    },
    {
        "time": "14:00",
        "mon": 2,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 10,
        "sun": 3,
    },
    {
        "time": "15:00",
        "mon": 20,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 0,
        "sun": 3,
    },
    {
        "time": "16:00",
        "mon": 50,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 2,
        "sun": 3,
    },
    {
        "time": "17:00",
        "mon": 30,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 2,
        "sun": 3,
    },
    {
        "time": "18:00",
        "mon": 20,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 2,
        "sun": 3,
    },
    {
        "time": "19:00",
        "mon": 2,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 2,
        "sun": 3,
    },
    {
        "time": "20:00",
        "mon": 50,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 1,
        "sun": 3,
    },
    {
        "time": "21:00",
        "mon": 11,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 9,
        "sun": 3,
    },
    {
        "time": "22:00",
        "mon": 20,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 3,
        "sun": 3,
    },
    {
        "time": "23:00",
        "mon": 5,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 2,
        "sun": 3,
    },
    {
        "time": "24:00",
        "mon": 10,
        "tue": 10,
        "wed": 9,
        "thur": 5,
        "fri": 1,
        "sat": 5,
        "sun": 3,
    },
]


